src/Entity/Video.php
<?php

namespace App\Entity;

use App\Entity\Category;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\VideoRepository;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Url;
use Symfony\Component\Validator\Constraints\NotBlank;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=VideoRepository::class)
 * @UniqueEntity(
 *     fields={"url"},
 *     errorPath="url",
 *     message="Cette vidéo existe déjà"
 * )
 */
class Video
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez indiquer un nom à la vidéo")
     */
    private $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(message="Veuillez indiquer une url valide")
     * @Assert\NotBlank(message="Veuillez indiquer une url")
     */
    private $url;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Veuillez indiquer une description")
     */
    private $description;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $author_link;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_best;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="videos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getAuthorLink(): ?string
    {
        return $this->author_link;
    }

    public function setAuthorLink(?string $author_link): self
    {
        $this->author_link = $author_link;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getIsBest(): ?bool
    {
        return $this->is_best;
    }

    public function setIsBest(bool $is_best): self
    {
        $this->is_best = $is_best;

        return $this;
    }
}

src/Form/VideoType.php
<?php

namespace App\Form;

use App\Entity\Video;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

class VideoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, ['label' => 'Titre de la vidéo : '])
            ->add('url', UrlType::class, ['label' => 'Url de la vidéo : '])
            ->add('description', CKEditorType::class, [
                'label' => 'Description : ',
                'config' => ['toolbar' => 'standard']
            ])
            ->add('author', TextType::class, ['label' => 'Auteur de la vidéo : '])
            ->add('author_link', UrlType::class, [
                'label' => 'Url du site de l\'auteur : ',
                'required' => false,
            ])
            ->add('is_best', CheckboxType::class, [
                'label' => 'Cochez la case si vous souhaitez la voir apparaitre dans les meilleures vidéos sur la page Accueil',
                'required' => false,
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'label' => 'Sélectionnez la catégorie : ',
                'attr' => [
                    'class' => 'form-select',
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Video::class,
        ]);
    }
}

src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Video;
use App\Form\VideoType;
use App\Form\SearchVideoType;
use App\Repository\VideoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/video", name="video_")
 */
class VideoController extends AbstractController
{
    /**
     * @Route("/", name="index", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(
        VideoRepository $videoRepository,
        Request $request
    ): Response {

        $form = $this->createForm(SearchVideoType::class);

        return $this->render('video/index.html.twig', [
            'videos' => $videoRepository->findBy([], ['title' => 'ASC',]),
            'formVideo' => $form->createView(),
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     * modifie l'url si y a l'indication &t= qui correspond à une durée dans une vidéo
     * 1ere lettre du titre de la video en masjuscule
     * 1ere lettre des mots de l'auteur en majuscule
     */
    public function new(Request $request, EntityManagerInterface $em): Response
    {
        $video = new Video();

        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (stripos($video->getUrl(), "&t=") !== FALSE) {
                $newUrl = strstr($video->getUrl(), "&t=", true);
                $video->setUrl($newUrl);
            }
            $video->setTitle(ucfirst(strtolower($video->getTitle())));
            $video->setAuthor(ucwords(strtolower($video->getAuthor())));
            $em->persist($video);
            $em->flush();

            $this->addFlash("success", "La vidéo a bien été ajoutée !");
            return $this->redirectToRoute('video_index');
        }

        return $this->render('video/new.html.twig', [
            'video' => $video,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="show", methods={"GET"})
     */
    public function show(Video $video): Response
    {
        return $this->render('video/show.html.twig', [
            'video' => $video,
        ]);
    }

    /**
     * @Route("/{slug}/edit", name="edit", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     * modifie l'url si y a l'indication &t= qui correspond à une durée dans une vidéo
     * 1ere lettre du titre de la video en masjuscule
     * 1ere lettre des mots de l'auteur en majuscule
     */
    public function edit(Request $request, Video $video, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (stripos($video->getUrl(), "&t=") !== FALSE) {
                $newUrl = strstr($video->getUrl(), "&t=", true);
                $video->setUrl($newUrl);
            }
            $video->setTitle(ucfirst(strtolower($video->getTitle())));
            $video->setAuthor(ucwords(strtolower($video->getAuthor())));
            $em->flush();
            $this->addFlash("success", "La vidéo a bien été modifiée !");
            return $this->redirectToRoute('video_index');
        }

        return $this->render('video/edit.html.twig', [
            'video' => $video,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}/delete", name="delete", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(
        Video $video,
        EntityManagerInterface $em,
        VideoRepository $videoRepository
    ): Response {

        $em->remove($video);
        $em->flush();

        $videos = $videoRepository->findBy([], ['title' => 'ASC',]);

        $arrayVideos = [];
        foreach ($videos as $key => $value) {
            $arrayVideos[$key]['id'] = $value->getId();
            $arrayVideos[$key]['title'] = $value->getTitle();
            $arrayVideos[$key]['slug'] = $value->getSlug();
            $arrayVideos[$key]['author'] = $value->getAuthor();
            $arrayVideos[$key]['category'] = $value->getCategory()->getName();
        }

        return new JsonResponse([
            'videos' => $arrayVideos,
        ]);
    }

    /**
     * @Route("/searchMovie/{search}", name="search_movie", methods={"GET", "POST"})
     */
    public function searchVideo(?String $search, VideoRepository $videoRepository): Response
    {
        if ($search == "all") {
            $videos = $videoRepository->findBy([], ['title' => 'ASC',]);
        } else {
            $videos = $videoRepository->findVideoBySearch($search);
        }

        $arrayVideos = [];
        foreach ($videos as $key => $value) {
            $arrayVideos[$key]['id'] = $value->getId();
            $arrayVideos[$key]['title'] = $value->getTitle();
            $arrayVideos[$key]['slug'] = $value->getSlug();
            $arrayVideos[$key]['url'] = $value->getUrl();
            $arrayVideos[$key]['author'] = $value->getAuthor();
            $arrayVideos[$key]['category'] = $value->getCategory()->getName();
        }

        return new JsonResponse([
            'videos' => $arrayVideos,
        ]);
    }
}

templates/video/_delete_form.html.twig
<form method="post" action="{{ path('video_delete', {'slug': video.slug}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer cette vidéo ?');">
	<input type="hidden" name="_method" value="DELETE">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ video.id) }}">
	<button class="btn">
		<i class="fas fa-trash fa-lg text-danger"></i>
	</button>
</form>

templates/video/_form.html.twig
{{ form_start(form) }}
<div class="form-group mb-3">
	{{ form_label(form.title) }}
	{{ form_widget(form.title) }}
</div>
<div class="form-group mb-3">
	{{ form_label(form.url) }}
	{{ form_widget(form.url) }}
</div>
<div class="form-group mb-3">
	{{ form_label(form.description) }}
	{{ form_widget(form.description) }}
</div>
<div class="form-group mb-3">
	{{ form_label(form.author) }}
	{{ form_widget(form.author) }}
</div>
<div class="form-group mb-3">
	{{ form_label(form.author_link) }}
	{{ form_widget(form.author_link) }}
</div>
<div class="form-group mb-3">
	{{ form_label(form.is_best) }}
	{{ form_widget(form.is_best) }}
</div>
<div class="form-group mb-3">
	{{ form_label(form.category) }}
	{{ form_widget(form.category) }}
</div>
<div class=" d-flex justify-content-center">
	<button class="btn btn-outline-primary btn-lg rounded-lg shadow">
		{{ button_label|default('Enregistrer') }}
	</button>
</div>
{{ form_end(form) }}

templates/video/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}myVideoPlayer || Mise à jour
	{{ video.title }}
{% endblock %}

{% block body %}
	<div class="row text-center pt-3 pb-3 mb-3 border-bottom bg-secondary text-white shadow">
		<h2>Mise à jour</h2>
	</div>
	<div class="row mx-auto p-5 mb-3 border rounded-lg shadow">
		<div class="alert alert-primary" role="alert">
			<i>Tous les champs
				<b>"sauf l'url' du site de l'auteur"</b>
				doivent être complétés !</i>
		</div>
		{{ include('video/_form.html.twig', {'button_label': 'Modifier'}) }}
	</div>
	<div class="row pt-3 pb-3 mb-5">
		<a class="btn btn-dark col-2 rounded-lg shadow" href="{{ path('video_index') }}">Retour</a>
	</div>
{% endblock %}

templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}myVideoPlayer || Liste des Vidéos
{% endblock %}

{% block body %}
	<div class="d-grid gap-3">
		<div class="row text-center pt-3 pb-3 border-bottom bg-secondary text-white shadow">
			<h2>Gestion des vidéos</h2>
		</div>
		<div class="row text-center pt-3 pb-3 border-bottom">
			<h3 class="pb-2 text-decoration-underline">Ajouter une vidéo :
			</h3>
			<a class="btn btn-primary col-1 mx-auto rounded-lg shadow" href="{{ path('video_new') }}">
				<i class="fas fa-plus text-white fa-lg"></i>
			</a>
		</div>
		<div class="row text-center pt-3 pb-3">
			<h3 class="pb-2 text-decoration-underline">Liste des vidéos :
			</h3>
			<div class="row mt-2 mb-4">
				{{ form_start(formVideo) }}
				<div class="my-custom-class-for-errors">
					{{ form_errors(formVideo) }}
				</div>
				<div class="row g-3 align-items-center">
					<div class="col-lg-2 col-sm-12">
						{{ form_label(formVideo.search,'Rechercher  : ', {'attr': {'class': 'form-label'}}) }}
					</div>
					<div class="col-lg-8 col-sm-10">
						{{ form_widget(formVideo.search, {'attr': {'class': 'form-control'}}) }}
					</div>
				</div>
				{{ form_end(formVideo) }}
			</div>
			<table class="table">
				<thead class="table-secondary">
					<tr>
						<th scope="col">Titre</th>
						<th scope="col">Catégorie</th>
						<th scope="col">Auteur</th>
						<th scope="col">Actions</th>
					</tr>
				</thead>
				<tbody id="table-video">
					{% for video in videos %}
						<tr>
							<td>{{video.title}}</td>
							<td>{{video.category.name}}</td>
							<td>{{video.author}}</td>
							<td class="d-flex justify-content-evenly">
								<a class="btn" href="{{ path('video_edit', {'slug': video.slug}) }}">
									<i class="fas fa-edit fa-lg text-success"></i>
								</a>
								<a class="btn js-delete" href="{{ path('video_delete', {'slug': video.slug}) }}">
									<i class="fas fa-trash fa-lg text-danger"></i>
								</a>
							</td>
						</tr>
					{% else %}
						<tr>
							<td>Aucune vidéo</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}

{% block javascripts %}
	<script src="/js/video-search.js"></script>
	<script src="/js/video-delete.js"></script>
	<script src="/js/alert-animation.js"></script>
{% endblock %}

templates/video/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}myVideoPlayer || Ajouter une vidéo
{% endblock %}

{% block body %}
	<div class="row text-center pt-3 pb-3 mb-3 border-bottom bg-secondary text-white shadow">
		<h2>Ajouter une vidéo</h2>
	</div>
	<div class="row mx-auto p-5 mb-3 border rounded-lg shadow">
		<div class="alert alert-primary" role="alert">
			<i>Tous les champs
				<b>"sauf l'url' du site de l'auteur"</b>
				doivent être complétés !</i>
		</div>
		{{ include('video/_form.html.twig') }}
	</div>
	<div class="row pt-3 pb-3 mb-5">
		<a class="btn btn-dark col-2 rounded-lg shadow" href="{{ path('video_index') }}">Retour</a>
	</div>
{% endblock %}

templates/video/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}myVideoPlayer ||
	{{ video.title }}
{% endblock %}

{% block body %}
	<div class="row p-5 mt-3 mb-2 text-center bg-light rounded border">
		<h2>{{ video.title }}</h1>
	</div>
	<div class="row p-1 pt-2 mb-2 bg-light rounded border">
		<div>{{ video.url|video_player|raw}}</div>
	</div>
	<div class="row p-5 mb-2 bg-light rounded border">
		<div>
			<b>Auteur :
			</b>
			{{ video.author}}</div>
		{% if video.authorLink %}
			<div>
				<b>Visiter le site de l'auteur :
				</b>
				<a class="btn btn-primary mr-3" href="{{video.authorLink}}" target="_blank" title="{{ video.author }}">
					<i class="fas fa-eye"></i>
					Découvrir
				</a>
			</div>
		{% endif %}
	</div>
	<div class="row p-5 mb-5 bg-light rounded border">
		<div>
			<b>Description :</b>
			{{video.description|raw}}</div>
	</div>
	<div class="row pt-3 pb-3 mb-5">
		<a class="btn btn-dark col-2 rounded-lg shadow" href="{{ path('category_show', {'slug': video.category.slug}) }}" title="Retour à la page catégorie {{video.category.slug}}">Retour</a>
	</div>
{% endblock %}